language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements/ci.txt
script:
  - coverage erase
  - coverage run --source=fixedwidth test_fixedwidth.py
  - coverage report --show-missing
  - flake8 fixedwidth --max-line-length=120 --max-complexity=4
